### ISSUE TITLE
appveyor ci support go1.12

### ISSUE THREAD

**Issue by appleboy** [go-ggz/ggz#80]
See the issue. https://github.com/appveyor/ci/issues/2875

**Comment by appleboy** [comment]
Add the following script

```
environment:
  GOPATH: c:\gopath
  GOVERSION: 1.12.4

install:
  # Install the specific Go version.
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
  - msiexec /i go%GOVERSION%.windows-amd64.msi /q
  - choco install bzr
  - go version
  - go env
```
